/**
 * DATABASE DELLE OPERE - I VOLTI DELL'IGNOTO
 * Percorso espositivo sull'angoscia, il perturbante e l'abisso.
 */

const widthMoltiplicator = 1.5; 

const exhibitionData = [
    {
        id: 1,
        title: "Saturno che divora i suoi figli",
        artist: "Francisco Goya",
        year: "1819-1823",
        tech: "Olio su tela",
        description: "Un'immagine di violenza ancestrale dove l'oscurità inghiotte tutto tranne il corpo smembrato e gli occhi folli del dio. Goya trasforma il mito in un incubo espressionista ante litteram.\n\nÈ la radice biologica dell'angoscia: il tempo che distrugge la sua stessa prole. Apre la mostra per sancire l'ineluttabilità della fine e preparare lo spettatore all'abisso.",
        color: "#ff7e5f",
        image: "assets/013.png",
        width: 0.81 * widthMoltiplicator,
        position: { x: 19, y: 2, z: 26.05 },
        rotation: { y: 0 }
    },
    {
        id: 2,
        title: "Monaco in riva al mare",
        artist: "Caspar David Friedrich",
        year: "1808-1810",
        tech: "Olio su tela",
        description: "Un uomo minuscolo davanti all'immensità di un cielo plumbeo e un mare nero. Friedrich annulla le coordinate spaziali per ritrarre la solitudine dell'anima.\n\nDialoga con Goya per contrasto: se Saturno è il terrore fisico, qui siamo di fronte all'angoscia spirituale del nulla. È il ponte verso l'ignoto metafisico.",
        color: "#2193b0",
        image: "assets/012.png",
        width: 1.7 * widthMoltiplicator,
        position: { x: 26.95, y: 2, z: 30.8 },
        rotation: { y: -Math.PI / 2 }
    },
    {
        id: 3,
        title: "L'isola dei morti",
        artist: "Arnold Bocklin,",
        year: "1883, terza versione",
        tech: "Olio su tela",
        description: "Un'imbarcazione silenziosa scivola verso un'isola di rocce e cipressi. L'opera è satura di un silenzio ipnotico e funereo, tipico del simbolismo nordico.\n\nChiude la prima sezione dedicata alla morte come 'luogo'. La sua staticità monumentale funge da soglia psicologica per entrare nel labirinto urbano della sala successiva.",
        color: "#cc2b5e",
        image: "assets/011.png",
        width: 1.5 * widthMoltiplicator,
        position: { x: 20, y: 2, z: 35.95 },
        rotation: { y: Math.PI }
    },
    {
        id: 4,
        title: "I Nottabuli (Nighthawks)",
        artist: "Edward Hopper",
        year: "1942",
        tech: "Olio su tela",
        description: "Un bar notturno sotto una luce elettrica cruda e fredda. La vetrata curva isola i personaggi dal resto del mondo, rendendoli spettatori della propria solitudine.\n\nInaugura il tema dell'angoscia urbana. Qui l'ignoto non è più la morte, ma l'altro: persone vicine nello spazio ma infinitamente distanti nell'anima.",
        color: "#56ab2f",
        image: "assets/022.png",
        width: 1.5 * widthMoltiplicator,
        position: { x: 26.95, y: 1.75, z: 19 },
        rotation: { y: -Math.PI / 2 }
    },
    {
        id: 5,
        title: "Tavola calda (Automat)",
        artist: "Edward Hopper",
        year: "1927",
        tech: "Olio su tela",
        description: "Una donna sola fissa il suo caffè. Alle sue spalle, il riflesso delle luci nel vetro suggerisce un vuoto artificiale che si estende all'infinito.\n\nAffiancata a Nighthawks per enfatizzare il tema del 'vuoto domestico' portato nello spazio pubblico. È l'angoscia del silenzio in mezzo alla modernità.",
        color: "#606c88",
        image: "assets/021.png",
        width: 0.9 * widthMoltiplicator,
        position: { x: 26.95, y: 1.75, z: 12 },
        rotation: { y: -Math.PI  / 2}
    },
    {
        id: 6,
        title: "Domenica di primo mattino",
        artist: "Edward Hopper",
        year: "1930",
        tech: "Olio su tela",
        description: "Una fila di negozi deserti sotto una luce radente che proietta ombre lunghe e inquietanti. La città sembra un palcoscenico vuoto prima o dopo una tragedia.\n\nRappresenta l'angoscia del deserto urbano. Introduce il senso di sospensione temporale che troverà pieno compimento nelle opere metafisiche di De Chirico poco distanti.",
        color: "#606c88",
        image: "assets/023.png",
        width: 1.5 * widthMoltiplicator,
        position: { x: 20.5, y: 1.75, z: 5.05 },
        rotation: { y: 0}
    },
    {
        id: 7,
        title: "Paesaggio urbano con camion",
        artist: "Mario Sironi",
        year: "1920",
        tech: "Olio su tela",
        description: "Volumi pesanti, colori terrei e un'atmosfera opaca. Il camion sembra un mostro inerte in una periferia che ha perso ogni traccia di umanità.\n\nFa da ponte tra il realismo di Hopper e la metafisica. Il cemento diventa un nuovo tipo di abisso, una prigione materiale che schiaccia l'individuo.",
        color: "#606c88",
        image: "assets/025.png",
        width: 0.6 * widthMoltiplicator,
        position: { x: 14.05, y: 1.75, z: 10 },
        rotation: { y: Math.PI  / 2}
    },
    {
        id: 8,
        title: "L'enigma dell'ora",
        artist: "Giorgio de Chirico",
        year: "1910-11",
        tech: "Olio su tela",
        description: "Un loggiato, un orologio che segna un tempo immobile e una luce irreale. La prospettiva è volutamente distorta per generare un senso di angoscia.\n\nInizia la sequenza metafisica. L'angoscia nasce dal sospetto che la realtà quotidiana sia solo una maschera che nasconde un mistero geometrico e insolubile.",
        color: "#606c88",
        image: "assets/024.png",
        width: 0.7 * widthMoltiplicator,
        position: { x: 14.05, y: 1.75, z: 17 },
        rotation: { y: Math.PI  / 2}
    },
    {
        id: 9,
        title: "Enigma di una giornata",
        artist: "Giorgio de Chirico",
        year: "1914",
        tech: "Olio su tela",
        description: "Una ciminiera, una torre distante e una statua solitaria in una piazza deserta. Il quadro emana un senso di attesa angosciante per qualcosa che è già accaduto o che non accadrà mai.\n\nServe a trasfigurare definitivamente lo spazio urbano di Hopper in uno spazio puramente mentale e onirico.",
        color: "#606c88",
        image: "assets/026.png",
        width: 1.4 * widthMoltiplicator,
        position: { x: 19, y: 1.75, z: 24.95 },
        rotation: { y: Math.PI }
    },
    {
        id: 10,
        title: "Enigma di un pomeriggio d’autunno",
        artist: "Giorgio de Chirico",
        year: "1910",
        tech: "Olio su tela",
        description: "Ispirato da una visione in Piazza Santa Croce a Firenze, questo dipinto segna la nascita della Metafisica. La realtà è spogliata della sua funzione e ridotta a simbolo.\n\nDopo aver esplorato la città, il visitatore viene introdotto al dubbio totale sulla natura della percezione.",
        color: "#606c88",
        image: "assets/031.png",
        width: 0.6 * widthMoltiplicator,
        position: { x: 8.5, y: 1.75, z: 24.95 },
        rotation: { y: Math.PI }
    },
    {
        id: 11,
        title: "La condizione umana I",
        artist: "René Magritte",
        year: "1933",
        tech: "Olio su tela",
        description: "Un quadro nel quadro. Il dipinto copre esattamente il paesaggio che sta dietro, oppure no? Ciò che vediamo o ciò che immaginiamo?\n\nIntroduce il tema dell'angoscia come \"incapacità di conoscere la verità\".",
        color: "#606c88",
        image: "assets/032.png",
        width: 0.8 * widthMoltiplicator,
        position: { x: 4.05, y: 1.75, z: 17.5 },
        rotation: { y: Math.PI / 2}
    },
    {
        id: 12,
        title: "La condizione umana II",
        artist: "René Magritte",
        year: "1935",
        tech: "Olio su tela",
        description: "Variante sul tema della percezione. Qui il cavalletto è all'interno di una stanza che sembra a sua volta un dipinto. La realtà diventa un labirinto di scatole cinesi.\n\nSegue la precedente per generare una sensazione di ossessione e vertigine logica. La mente non trova più un punto d'appoggio sicuro.",
        color: "#606c88",
        image: "assets/033.png",
        width: 0.8 * widthMoltiplicator,
        position: { x: 4.05, y: 1.75, z: 11 },
        rotation: { y: Math.PI / 2}
    },
    {
        id: 13,
        title: "La persistenza della memoria",
        artist: "Salvador Dalí",
        year: "1931",
        tech: "Olio su tela",
        description: "Gli iconici orologi molli simboleggiano la relatività del tempo psicologico, che si dilata e si scioglie sotto la pressione del sogno e del desiderio.\n\nRappresenta la perdita delle coordinate oggettive. Anche l'ultima certezza dell'uomo - il tempo che scorre - viene dichiarata fallace.",
        color: "#606c88",
        image: "assets/035.png",
        width: 0.5 * widthMoltiplicator,
        position: { x: 4.05, y: 1.75, z: 4 },
        rotation: { y: Math.PI / 2}
    },
    {
        id: 14,
        title: "Gli Amanti",
        artist: "René Magritte",
        year: "1928",
        tech: "Olio su tela",
        description: "Due figure tentano di baciarsi con i volti coperti da lenzuoli bianchi. È il simbolo supremo dell'impossibilità di conoscere davvero l'altro.\n\nPosta vicino ad American Gothic per esplorare l'angoscia nelle relazioni. Il velo di Magritte è l'equivalente psicologico della rigidità di Wood: un segreto inaccessibile.",
        color: "#606c88",
        image: "assets/034.png",
        width: 0.73 * widthMoltiplicator,
        position: { x: 12.95, y: 1.75, z: 14.5 },
        rotation: { y: -Math.PI / 2}
    },
    {
        id: 15,
        title: "American Gothic",
        artist: "Grant Wood",
        year: "1930",
        tech: "Olio su tela",
        description: "Un ritratto frontale che trasuda severità e rigore puritano. Gli sguardi ostili e la finestra oscurata suggeriscono un mondo domestico oscuro e angosciante.\n\nChiude la galleria dell'Enigma. Rappresenta il 'perturbante' nel quotidiano: l'angoscia che si nasconde dietro una facciata di assoluta normalità e ordine.",
        color: "#606c88",
        image: "assets/036.png",
        width: 0.62 * widthMoltiplicator,
        position: { x: 12.95, y: 1.75, z: 9 },
        rotation: { y: -Math.PI / 2}
    },
    {
        id: 16,
        title: "L'impero delle luci",
        artist: "René Magritte",
        year: "1954",
        tech: "Olio su tela",
        description: "Una villetta immersa nell'oscurità notturna sotto un cielo diurno. La convivenza di due tempi opposti genera una calma profondamente innaturale e sinistra.\n\nFunziona come una bussola impazzita. È il punto di rottura prima del climax: la realtà non è solo dubbia, è diventata intrinsecamente impossibile.",
        color: "#606c88",
        image: "assets/041.png",
        width: 1.3 * widthMoltiplicator,
        position: { x: 20, y: 2, z: -1.95 },
        rotation: { y: 0},
        lightIntensity: 1,
    },
    {
        id: 17,
        title: "La Torre Rossa ad Halle",
        artist: "Ernst Ludwig Kirchner",
        year: "1915",
        tech: "Olio su tela",
        description: "Pennellate spezzate e colori acidi per una visione urbana traumatica. Kirchner deforma l'architettura per riflettere il collasso psichico dell'uomo durante la guerra.\n\nIl rosso violento prepara l'occhio e l'anima del visitatore alla drammaticità cromatica e formale dell'urlo collettivo di Guernica.",
        color: "#606c88",
        image: "assets/042.png",
        width: 0.91 * widthMoltiplicator,
        position: { x: 20, y: 1.75, z: 3.95 },
        rotation: { y: Math.PI }
    },
    {
        id: 18,
        title: "Guernica",
        artist: "Pablo Picasso",
        year: "1937",
        tech: "Olio su tela",
        description: "Il capolavoro del XX secolo. Il dolore non è più privato ma universale. La distruzione dei corpi è resa attraverso la distruzione della forma cubista.\n\nÈ il fulcro drammatico della mostra: l'angoscia della storia che travolge l'umanità.",
        color: "#606c88",
        image: "assets/051.png",
        width: 7.7 * widthMoltiplicator,
        position: { x: 8.5, y: 3, z: -21.95 },
        rotation: { y: 0 },
        lightAngle: Math.PI
    },
    {
        id: 19,
        title: "Studio dal ritratto di Innocenzo X",
        artist: "Francis Bacon",
        year: "1953",
        tech: "Olio su tela",
        description: "Il pontefice è intrappolato in una struttura a gabbia, il volto deformato da un grido silenzioso. La carne sembra sciogliersi in strisce verticali di colore.\n\nRappresenta l'autorità che crolla e l'individuo prigioniero del proprio trauma. Dialoga con la violenza di Picasso, portandola in una dimensione claustrofobica.",
        color: "#606c88",
        image: "assets/053.png",
        width: 1.18 * widthMoltiplicator,
        position: { x: 22.95, y: 2, z: -17.5 },
        rotation: { y: -Math.PI / 2 }
    },
    {
        id: 20,
        title: "Il grido",
        artist: "Edvard Munch",
        year: "1893",
        tech: "Olio su tela",
        description: "Un paesaggio che vibra insieme all'anima. L'urlo non esce dalla bocca, ma attraversa tutta la natura circostante.\n\nPosta vicino a Guernica come risposta individuale al dolore universale.",
        color: "#606c88",
        image: "assets/052.png",
        width: 0.73 * widthMoltiplicator,
        position: { x: -4, y: 1.75, z: -21.95 },
        rotation: { y: 0 }
    },
    {
        id: 21,
        title: "I mangiatori di patate",
        artist: "Vincent Van Gogh",
        year: "1885",
        tech: "Olio su tela",
        description: "L'oscurità terrosa avvolge contadini dai volti scavati. È un omaggio alla fatica ancestrale e alla dignità disperata di chi vive di stenti.\n\nRadica l'angoscia nella realtà materiale e nella povertà. Offre un contrappunto 'terreno' e scuro agli urli metafisici e storici delle opere vicine.",
        color: "#606c88",
        image: "assets/055.png",
        width: 1.14 * widthMoltiplicator,
        position: { x: -12, y: 1.75, z: -21.95 },
        rotation: { y: 0 }
    },
    {
        id: 22,
        title: "L'intrigo",
        artist: "James Ensor",
        year: "1890",
        tech: "Olio su tela",
        description: "Una parata di maschere grottesche e deformi circonda il visitatore. La società è vista come un raduno di mostri ipocriti e feroci.\n\nChiude la sala del climax. Rappresenta l'orrore del giudizio sociale e della folla.",
        color: "#606c88",
        image: "assets/054.png",
        width: 1.5 * widthMoltiplicator,
        position: { x: -2, y: 1.75, z: -13.05 },
        rotation: { y: Math.PI }
    },
    {
        id: 23,
        title: "Notte stellata",
        artist: "Vincent Van Gogh",
        year: "1889",
        tech: "Olio su tela",
        description: "Il cielo è un mare in tempesta. I cipressi sono fiamme nere. È la proiezione di una mente che non trova pace nemmeno nell'infinito.\n\nL'ignoto qui è un turbine cosmico che affascina e terrorizza.",
        color: "#606c88",
        image: "assets/061.png",
        width: 1 * widthMoltiplicator,
        position: { x: -28.95, y: 1.75, z: -13 },
        rotation: { y: Math.PI /2 }
    },
    {
        id: 24,
        title: "Chiesa di Auverns-sur-Oise",
        artist: "Vincent Van Gogh",
        year: "1890",
        tech: "Olio su tela",
        description: "Le pareti della chiesa sembrano sciogliersi e il terreno ondeggiare. Il cielo blu profondo incombe come un peso insopportabile sull'architettura sacra.\n\nSegue la Notte Stellata per mostrare come l'angoscia interiore arrivi a minare persino la stabilità visiva dei luoghi di culto e della comunità.",
        color: "#606c88",
        image: "assets/062.png",
        width: 0.75 * widthMoltiplicator,
        position: { x: -28.95, y: 1.75, z: -4 },
        rotation: { y: Math.PI /2 }
    },
    {
        id: 25,
        title: "Crepuscolo: albero rosso",
        artist: "Piet Mondrian",
        year: "1908-09",
        tech: "Olio su tela",
        description: "Un albero scheletrico reso con pennellate di un rosso fiammeggiante su uno sfondo blu cobalto. È la natura che si trasforma in pura emozione nervosa.\n\nUltimo sguardo alla natura prima della frammentazione. Prepara il terreno al Futurismo, dove l'angoscia si fonderà con la velocità e la scomposizione.",
        color: "#606c88",
        image: "assets/063.png",
        width: 1 * widthMoltiplicator,
        position: { x: -28.95, y: 1.75, z: 5 },
        rotation: { y: Math.PI /2 }
    },
    {
        id: 26,
        title: "Stati d'animo. Quelli che vanno",
        artist: "Umberto Boccioni",
        year: "1911",
        tech: "Olio su tela",
        description: "Linee oblique e veloci scompongono i corpi e il paesaggio visto dal treno. Il movimento diventa una fuga disperata dall'identità.\n\nRappresenta l'angoscia della fuga. Qui l'ignoto è il futuro, un orizzonte che si frantuma in un dinamismo violento e instabile.",
        color: "#606c88",
        image: "assets/064.png",
        width: 1 * widthMoltiplicator,
        position: { x: -19.05, y: 1.75, z: 7 },
        rotation: { y: -Math.PI /2 }
    },
    {
        id: 27,
        title: "Stati d'animo. Quelli che restano",
        artist: "Umberto Boccioni",
        year: "1911",
        tech: "Olio su tela",
        description: "Linee verticali pesanti e cupe descrivono figure che sembrano trascinarsi nel fango. È il dolore sordo di chi viene abbandonato dal progresso.\n\nL'angoscia della stasi dopo la tempesta del movimento. Fa riflettere sul senso di vuoto che rimane dopo ogni trauma.",
        color: "#606c88",
        image: "assets/065.png",
        width: 1 * widthMoltiplicator,
        position: { x: -19.05, y: 1.75, z: -2 },
        rotation: { y: -Math.PI / 2 }
    },
    {
        id: 28,
        title: "Stati d'animo. Gli addii",
        artist: "Umberto Boccioni",
        year: "1911",
        tech: "Olio su tela",
        description: "Il vapore, i fischi del treno e gli abbracci che si dissolvono in linee di forza. La separazione fisica diventa una frammentazione dell'anima.\n\nChiude il ciclo futurista. L'angoscia che deriva dallo sradicamento e dalla perdita dei legami.",
        color: "#606c88",
        image: "assets/066.png",
        width: 1 * widthMoltiplicator,
        position: { x: -19.05, y: 1.75, z: -11 },
        rotation: { y: -Math.PI / 2 }
    },
    {
        id: 29,
        title: "La camera da letto",
        artist: "Vincent Van Gogh",
        year: "1888",
        tech: "Olio su tela",
        description: "Colori apparentemente vivaci, ma una prospettiva sghemba e mobili troppo vicini che creano un senso di instabilità e claustrofobia.\n\nUna stanza dentro la stanza. Rappresenta il tentativo fallito di trovare un rifugio sicuro nell'intimità.",
        color: "#606c88",
        image: "assets/071.png",
        width: 0.91 * widthMoltiplicator,
        position: { x: -17.95, y: 1.75, z: -8 },
        rotation: { y: Math.PI / 2 }
    },
    {
        id: 30,
        title: "La bambina malata",
        artist: "Edvard Munch",
        year: "1885-86",
        tech: "Olio su tela",
        description: "Un'opera graffiata, quasi ferita nella sua materia pittorica. Munch ritrae il momento del passaggio, la rassegnazione e lo strazio silenzioso del ricordo.\n\nDopo gli urli universali e i turbini cosmici, rimane solo il dolore privato. È il cerchio che si chiude, tornando all'ignoto della morte con cui la mostra era iniziata.",
        color: "#606c88",
        image: "assets/072.png",
        width: 1.2 * widthMoltiplicator,
        position: { x: 2.95, y: 1.75, z: -8 },
        rotation: { y: -Math.PI /2 }
    }
];

/**
 * DATABASE DEI CARTELLI (TESTI)
 * Puoi aggiungere cartelli informativi o indicazioni.
 */
const signData = [
    {
        id: "sign-welcome",
        text: "BENVENUTI AL\nACCADEMIA DI FIRENZE\n\nSeguite il percorso\nper esplorare le opere",
        position: { x: 8.6, y: 3.5, z: 26.001 },
        rotation: { y: 0 },
        fontSize: 70,
        textColor: "#ffffff",
        bgColor: "rgba(0, 0, 0, 0.7)",
        width: 6
    },
    {
        id: "arr-1",
        text: "-->",
        position: { x: 8.6, y: 1.5, z: 26.001 },
        rotation: { y: 0 },
        fontSize: 300,
        textColor: "#ffffff",
        bgColor: "rgba(0, 0, 0, 0.7)",
        width: 1.5
    },
    {
        id: "sala-1",
        text: "Sala 1:\n\nL'abisso\ndelle origini",
        position: { x: 15, y: 3, z: 26.05 },
        rotation: { y: 0 },
        fontSize: 70,
        textColor: "#000000",
        bgColor: "#cdcdcd",
        width: 2
    },
    {
        id: "sala-2",
        text: "Sala 2:\n\nIl silenzio\ndelle città",
        position: { x: 26.95, y: 3, z: 23 },
        rotation: { y: -Math.PI / 2 },
        fontSize: 70,
        textColor: "#000000",
        bgColor: "#cdcdcd",
        width: 2
    },
    {
        id: "sala-3",
        text: "Sala 3:\n\nIl dubbio della\npercezione",
        position: { x: 4.05, y: 3, z: 23 },
        rotation: { y: Math.PI / 2 },
        fontSize: 70,
        textColor: "#000000",
        bgColor: "#cdcdcd",
        width: 2
    },
    {
        id: "sala-4",
        text: "Sala 4:\n\nLa luce\ndisturbante",
        position: { x: 26.95, y: 3, z: 1 },
        rotation: { y: -Math.PI / 2 },
        fontSize: 70,
        textColor: "#000000",
        bgColor: "#cdcdcd",
        width: 2
    },
    {
        id: "sala-5",
        text: "Sala 5:\n\nIl climax\ndell'urlo",
        position: { x: 4.05, y: 3, z: -10 },
        rotation: { y: Math.PI / 2 },
        fontSize: 70,
        textColor: "#000000",
        bgColor: "#cdcdcd",
        width: 2
    },
    {
        id: "sala-6",
        text: "Sala 6:\n\nIl turbine e\nil congedo",
        position: { x: -28.95, y: 3, z: -18 },
        rotation: { y: Math.PI / 2 },
        fontSize: 70,
        textColor: "#000000",
        bgColor: "#cdcdcd",
        width: 2
    },
    {
        id: "sala-7",
        text: "Sala 7:\n\nLe stanze\ndella memoria",
        position: { x: -5, y: 3, z: -4.05 },
        rotation: { y: Math.PI },
        fontSize: 70,
        textColor: "#000000",
        bgColor: "#cdcdcd",
        width: 2
    },
    {
        id: "exit-1",
        text: "USCITA\n\n|\nV",
        position: { x: -8.5, y: 5, z: -4.05 },
        rotation: { y: Math.PI },
        fontSize: 70,
        textColor: "#ffcc00",
        bgColor: "#111111",
        width: 2
    },
    {
        id: "thank-you",
        text: "Grazie per aver visitato l'Academia di Firenze!\n\nSperiamo che questo viaggio nell'ignoto\nvi abbia emozionato e fatto riflettere.",
        position: { x: 0, y: 2.5, z: 29.95 },
        rotation: { y: Math.PI },
        fontSize: 40,
        textColor: "#2a2c47",
        bgColor: "#a5a591",
        width: 5
    },
    {
        id: "copyright",
        text: "© 2026 @simdlldev\nTutti i diritti riservati",
        position: { x: 0, y: 0.85, z: 29.96 },
        rotation: { y: Math.PI },
        fontSize: 40,
        textColor: "#2a2c47",
        bgColor: "#92846D",
        width: 2
    },
    {
        id: "sign-exit",
        text: "USCITA ->",
        position: { x: -50, y: 2.5, z: 5 },
        rotation: { y: Math.PI / 2 },
        fontSize: 48,
        textColor: "#ffcc00",
        bgColor: "#111111",
        width: 1.5
    }
];
